name: Release

on:
  push:
    tags: ["v*.*.*"]

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with: { python-version: "3.12" }
      - run: pip install build
      - run: python -m build
      - uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844  # v1
        with:
          files: dist/*
          generate_release_notes: true
